name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.GH_PAT }}
          persist-credentials: true

      - name: Prepare for production
        run: |
          rm .gitignore
          mv .deploy.gitignore .gitignore
          rm -rf .github
          rm -rf .idea
          rm -rf .vscode
          rm -rf assets
          rm -rf scss

      - name: Create a built branch
        run: |
          BRANCH_NAME=$(echo ${{ github.ref }} | sed 's|refs/heads/||')
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b $BRANCH_NAME-built
          git add -A && git commit -m "built from ${{ github.sha }}"
          git push --force -u origin $BRANCH_NAME-built
