name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Prepare for production
        run: |
          rm .gitignore
          mv .deploy.gitignore .gitignore
          rm -rf .github
          rm -rf .idea
          rm -rf .vscode
          rm -rf assets
          rm -rf scss

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/pluginverse/ultimate-posts-widget.git

      - name: Create a built branch
        run: |
          BRANCH_NAME=$(echo $GITHUB_REF | grep -oP '(?<=refs\/heads\/).*')
          git checkout -b $BRANCH_NAME-built
          git add -A && git commit -m "built from $GITHUB_SHA"
          git push --force -u origin $BRANCH_NAME-built
